### ISSUE TITLE
TestToggle 컴포넌트에서 setSearchParams 삭제

### ISSUE THREAD

**Issue by goleedev** [lttlsunshn/voca_test_01#10]
사용하지 않는 setSearchParams는 삭제해도 똑같이 작동하는 것으로 알고 있습니다!
해당 부분 확인 부탁드립니다!!

**Comment by lttlsunshn** [comment]
그렇잖아도 삭제하고 싶었는데, 에러가 생겨서요.
const searchParams = useSearchParams();
이렇게 하면 자꾸 에러가 납니다 ;;;

**Comment by goleedev** [comment]
> 그렇잖아도 삭제하고 싶었는데, 에러가 생겨서요. const searchParams = useSearchParams(); 이렇게 하면 자꾸 에러가 납니다 ;;;

const [searchParams] = useSearchParams();

혹시 이렇게 남겨주셔도 에러가 나나유??
