### ISSUE TITLE
console.log 및 주석처리된 코드 삭제

### ISSUE THREAD

**Issue by goleedev** [lttlsunshn/voca_test_01#3]
**Description**

개발 시에 디버깅 용으로 console.log를 찍어서 확인할 수 있지만,
배포 코드에 올리는 경우 없기에 해당 부분 삭제 부탁드립니다!

또한, 같은 맥락으로 주석처리의 이유가 따로 없다면 삭제해주시는 것이 좋을 듯 합니다!

**Comment by lttlsunshn** [comment]
SOJU2 branch에 수정해 보았습니다 !!!

**Comment by goleedev** [comment]
@lttlsunshn 해당 이슈 pr 확인 완료 및 승인하였습니다 👍

**Comment by lttlsunshn** [comment]
감사합니다 !!!
