### ISSUE TITLE
uuid 라이브러리 => 자체 함수로 변경

### ISSUE THREAD

**Issue by goleedev** [lttlsunshn/voca_test_01#4]
**Description**

unique id를 사용하기 위해 uuid를 사용하시는 것은 너무 좋습니다!!
다만, uuid 라이브러리 대신에 자체적으로 함수를 만들어 보실 수 있을 것 같은데...!

`src > utils` 폴더를 생성하고 `uuid` 함수를 만들어서 사용해보시면 좋을 듯 합니다!!

**Comment by goleedev** [comment]
해당 이슈 review 확인 부탁드립니다!! 👍

**Comment by lttlsunshn** [comment]
넵~
