### ISSUE TITLE
SortContext 위치 및 이름 변경

### ISSUE THREAD

**Issue by goleedev** [lttlsunshn/voca_test_01#9]
SortContext는 최종적으로 sorting하는 provider를 반환하므로, components 안에 위치하는 것이 맞다고 생각합니다!!
또한, Provider를 반환하여 사용하는만큼 export default SortProvider 로 변경해주시면 좋지 않을 까 생각합니다 👍

**Comment by lttlsunshn** [comment]
SortContext.js는 components 폴더로 옮기고 PR 했습니다.
export default SortProvider로 바꾸려 하니 에러가 나서 'default'는 넣지 못했습니다.

**Comment by goleedev** [comment]
> SortContext.js는 components 폴더로 옮기고 PR 했습니다. export default SortProvider로 바꾸려 하니 에러가 나서 'default'는 넣지 못했습니다.

export default function SortProvider 이렇게 function 혹은 const를 넣어주어야 하는데 오타를 내었습니다 !! 😢

**Comment by goleedev** [comment]
@lttlsunshn 

넵!! default를 붙이면 `import SortProvider from "./components/SortContext"`로 import할 수 있고
default를 붙이지 않고 import하면 `import { SortProvider } from "./components/SortContext"`로 import할 수 있습니다!!

**Comment by goleedev** [comment]
@lttlsunshn 

```
export default function SortProvider({ children }) {
...
}
```

**Comment by lttlsunshn** [comment]
감사합니다 !!! SOJU16으로 PR하였습니다~~

**Comment by goleedev** [comment]
approve 했습니다!
